package com.pinyougou.pojo;

import java.io.Serializable;

public class TbCities implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cities.id
     *
     * @mbg.generated Tue Nov 20 19:21:23 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cities.cityid
     *
     * @mbg.generated Tue Nov 20 19:21:23 CST 2018
     */
    private String cityid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cities.city
     *
     * @mbg.generated Tue Nov 20 19:21:23 CST 2018
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cities.provinceid
     *
     * @mbg.generated Tue Nov 20 19:21:23 CST 2018
     */
    private String provinceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_cities
     *
     * @mbg.generated Tue Nov 20 19:21:23 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cities.id
     *
     * @return the value of tb_cities.id
     *
     * @mbg.generated Tue Nov 20 19:21:23 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cities.id
     *
     * @param id the value for tb_cities.id
     *
     * @mbg.generated Tue Nov 20 19:21:23 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cities.cityid
     *
     * @return the value of tb_cities.cityid
     *
     * @mbg.generated Tue Nov 20 19:21:23 CST 2018
     */
    public String getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cities.cityid
     *
     * @param cityid the value for tb_cities.cityid
     *
     * @mbg.generated Tue Nov 20 19:21:23 CST 2018
     */
    public void setCityid(String cityid) {
        this.cityid = cityid == null ? null : cityid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cities.city
     *
     * @return the value of tb_cities.city
     *
     * @mbg.generated Tue Nov 20 19:21:23 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cities.city
     *
     * @param city the value for tb_cities.city
     *
     * @mbg.generated Tue Nov 20 19:21:23 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cities.provinceid
     *
     * @return the value of tb_cities.provinceid
     *
     * @mbg.generated Tue Nov 20 19:21:23 CST 2018
     */
    public String getProvinceid() {
        return provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cities.provinceid
     *
     * @param provinceid the value for tb_cities.provinceid
     *
     * @mbg.generated Tue Nov 20 19:21:23 CST 2018
     */
    public void setProvinceid(String provinceid) {
        this.provinceid = provinceid == null ? null : provinceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cities
     *
     * @mbg.generated Tue Nov 20 19:21:23 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", cityid=").append(cityid);
        sb.append(", city=").append(city);
        sb.append(", provinceid=").append(provinceid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}